// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzDeId-Pz1uN1ORG7oEQoxS-CvYdkmAws',
    appId: '1:367048092022:web:eee09fb6f0a7ed66297257',
    messagingSenderId: '367048092022',
    projectId: 'car-rent-practicee',
    authDomain: 'car-rent-practicee.firebaseapp.com',
    storageBucket: 'car-rent-practicee.firebasestorage.app',
    measurementId: 'G-0T2JNN08S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIDIJHDocBzn4jy-jFfbSXyPhYFwJAW2E',
    appId: '1:367048092022:android:e85c8dbe92585943297257',
    messagingSenderId: '367048092022',
    projectId: 'car-rent-practicee',
    storageBucket: 'car-rent-practicee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Pw7FGyxWMfDS2isZYq_aBh_jefA2e0E',
    appId: '1:367048092022:ios:b22a2fc2f9f982c9297257',
    messagingSenderId: '367048092022',
    projectId: 'car-rent-practicee',
    storageBucket: 'car-rent-practicee.firebasestorage.app',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzDeId-Pz1uN1ORG7oEQoxS-CvYdkmAws',
    appId: '1:367048092022:web:609cfeb275b1ff4d297257',
    messagingSenderId: '367048092022',
    projectId: 'car-rent-practicee',
    authDomain: 'car-rent-practicee.firebaseapp.com',
    storageBucket: 'car-rent-practicee.firebasestorage.app',
    measurementId: 'G-K45K2FBCDS',
  );

}