// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeA6tSmnuVxUDH9GvRrfMY3yMKGhvEXsw',
    appId: '1:338142616870:web:32f48df7b95ff5d39075e7',
    messagingSenderId: '338142616870',
    projectId: 'to-do-a185e',
    authDomain: 'to-do-a185e.firebaseapp.com',
    storageBucket: 'to-do-a185e.firebasestorage.app',
    measurementId: 'G-DR8S3CDYVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYoNfjWoP13Z7HfdS6VZUNsTSeWkhWe1o',
    appId: '1:338142616870:android:5c113c946b5705e79075e7',
    messagingSenderId: '338142616870',
    projectId: 'to-do-a185e',
    storageBucket: 'to-do-a185e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyByLJ-EurLcciHGi0UBdk5yz_C_RaV70',
    appId: '1:338142616870:ios:2f3be2c4cadd3dc29075e7',
    messagingSenderId: '338142616870',
    projectId: 'to-do-a185e',
    storageBucket: 'to-do-a185e.firebasestorage.app',
    iosClientId: '338142616870-6329e7noqqh456p8vbql27ek2spl3jed.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeA6tSmnuVxUDH9GvRrfMY3yMKGhvEXsw',
    appId: '1:338142616870:web:daa3239075c3e8db9075e7',
    messagingSenderId: '338142616870',
    projectId: 'to-do-a185e',
    authDomain: 'to-do-a185e.firebaseapp.com',
    storageBucket: 'to-do-a185e.firebasestorage.app',
    measurementId: 'G-XMGSB3SWP0',
  );
}
